name: CI

permissions: {}

on:
  pull_request:
  push:
    branches:
      - alpha
      - beta
      - main
      - renovate/**

jobs:
  ci-optimization:
    name: CI optimization
    uses: dargmuesli/github-actions/.github/workflows/ci-optimization.yml@0ee6252ffb1543f94dbf5acd108d1affd8b787d0 # 5.2.4
    permissions:
      pull-requests: read
  build:
    needs: ci-optimization
    if: needs.ci-optimization.outputs.continue == 'true'
    name: Build
    uses: dargmuesli/github-actions/.github/workflows/docker.yml@0ee6252ffb1543f94dbf5acd108d1affd8b787d0 # 5.2.4
    permissions:
      packages: write
    with:
      PUSH: false
