name: CI

permissions: {}

on:
  pull_request:
  push:
    branches:
      - alpha
      - beta
      - main
      - renovate/**

jobs:
  ci-optimization:
    name: CI optimization
    uses: dargmuesli/github-actions/.github/workflows/ci-optimization.yml@2fb9bdae5c8ce52ea7f9546d1ba22c34921246de # 5.1.3
    permissions:
      pull-requests: read
  build:
    needs: ci-optimization
    if: needs.ci-optimization.outputs.continue == 'true'
    name: Build
    uses: dargmuesli/github-actions/.github/workflows/docker.yml@2fb9bdae5c8ce52ea7f9546d1ba22c34921246de # 5.1.3
    permissions:
      packages: write
    with:
      PUSH: false
